[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-project"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/boatlogo.png"
favicon = "images/boat.png"
primaryColor = "dark"

[data.sample_csv]
type = "csv"
path = "data/titanic.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
